const postConstant={
    GET_POSTS:"GET_POSTS",
    ADD_POST:"ADD_POST",
    GET_REJECT_POSTS:"GET_REJECT_POSTS",
    GET_WAITING_POSTS:"GET_WAITING_POSTS",
    GET_SHOWING_POSTS:"GET_SHOWING_POSTS"
}

export default postConstant;