const postConstant={
    GET_POSTS:"GET_POSTS",
    ADD_POST:"ADD_POST",
    GET_REJECT_POSTS:"GET_REJECT_POSTS",
    GET_WAITING_POSTS:"GET_WAITING_POSTS",
    GET_SHOWING_POSTS:"GET_SHOWING_POSTS",
    GET_TYPE_POSTS:"GET_TYPE_POSTS",
    PHONG_TRO_TYPE:"Phòng trọ",
    NHA_NGUYEN_CAN_TYPE:"Nhà nguyên căn",
    CAN_HO_TYPE:"Căn hộ",
    GET_POST_DETAIL_ADMIN:"GET_POST_DETAIL_ADMIN",
    GET_POST_DETAIL:"GET_POST_DETAIL",
    GET_RELATED_POSTS:"GET_RELATED_POSTS",
    GET_NEW_POSTS:"GET_NEW_POSTS"
}

export default postConstant;